version: "2"
services:
  web:
    build: ./nginx
    container_name: api-front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    links:
      - authorization:authorization
  authorization:
    build: ./authorization
    container_name: api-authorization
